FROM python:3.11

# Set the working directory in the container
RUN mkdir /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the models' state dictionaries
COPY /model_dict /model_dict

# Copy the rest of the application code into the container
COPY . .

# Expose the app to gunicorn through port 8000 of the container
EXPOSE 8000

# Start the server to run the application
CMD ["gunicorn", "main:app", "-b", "0.0.0.0:8000", "-c", "gunicorn.conf.py"]