FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose the app to gunicorn through port 3100 of the container
EXPOSE 3100

# Start the server to run the application
CMD ["gunicorn", "main:app"]